#!/usr/bin/env node

/**
 * Convert *.locale.json files to .po (gettext) format
 *
 * Usage: node tools/convert-locales.js
 */

const fs = require('fs');
const path = require('path');

const ROOT_DIR = path.resolve(__dirname, '..');

/**
 * Find all locale JSON files recursively
 */
function findLocaleFiles(dir = ROOT_DIR) {
  const files = [];

  function walk(currentPath) {
    const entries = fs.readdirSync(currentPath, { withFileTypes: true });

    for (const entry of entries) {
      // Skip node_modules, dist, coverage, .git, etc.
      if (
        entry.name.startsWith('.') ||
        entry.name === 'node_modules' ||
        entry.name === 'dist' ||
        entry.name === 'coverage'
      ) {
        continue;
      }

      const fullPath = path.join(currentPath, entry.name);

      if (entry.isDirectory()) {
        walk(fullPath);
      } else if (entry.isFile() && entry.name.match(/\.locales?\.json$/i)) {
        files.push(fullPath);
      }
    }
  }

  walk(dir);
  return files;
}

/**
 * Recursively flatten a nested object into key-value pairs
 * @param {*} obj - The object to flatten
 * @param {string} prefix - The prefix for keys
 * @returns {Object} Flattened object with full paths as keys
 */
function flattenObject(obj, prefix = '') {
  const result = {};

  function flatten(current, key) {
    if (typeof current === 'string' || typeof current === 'number') {
      result[key] = String(current);
    } else if (typeof current === 'object' && current !== null && !Array.isArray(current)) {
      for (const [childKey, childValue] of Object.entries(current)) {
        const newKey = key ? `${key}.${childKey}` : childKey;
        flatten(childValue, newKey);
      }
    }
    // Ignore arrays and other types
  }

  for (const [key, value] of Object.entries(obj)) {
    flatten(value, key);
  }

  return result;
}

/**
 * Convert a flattened object to PO format
 * @param {Object} entries - Flattened key-value pairs
 * @param {string} fileName - The source file name
 * @param {string} language - The language code (e.g., 'en', 'de')
 * @returns {string} PO file content
 */
function generatePoContent(entries, fileName, language = '') {
  const now = new Date();
  const timestamp = now.toISOString().replace('T', ' ').slice(0, -5) + '+0000';

  let content = `# Translation file for ${fileName}
# Auto-generated by convert-locales.js
msgid ""
msgstr ""
"Content-Type: application/x-po; charset=UTF-8\\n"
"Language: ${language}\\n"
"Project-Id-Version: \\n"
`;

  for (const [key, value] of Object.entries(entries).sort()) {
    content += `msgid "${escapePoString(key)}"\n`;
    content += `msgstr "${escapePoString(value)}"\n\n`;
  }

  return content;
}

/**
 * Escape special characters for PO format
 * @param {string} str - String to escape
 * @returns {string} Escaped string
 */
function escapePoString(str) {
  return str
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"')
    .replace(/\n/g, '\\n')
    .replace(/\r/g, '\\r')
    .replace(/\t/g, '\\t');
}

/**
 * Main conversion function
 */
function main() {
  const localeFiles = findLocaleFiles();

  if (localeFiles.length === 0) {
    console.log('No locale JSON files found.');
    return;
  }

  console.log(`Found ${localeFiles.length} locale file(s):\n`);

  let convertedCount = 0;

  for (const filePath of localeFiles) {
    try {
      const content = fs.readFileSync(filePath, 'utf-8');
      const data = JSON.parse(content);
      const flattened = flattenObject(data);

      // Extract language code from filename (e.g., 'en' from 'en.locales.json')
      const fileName = path.basename(filePath);
      const languageMatch = fileName.match(/^([a-z]{2}(?:-[a-z]{2})?)/i);
      const language = languageMatch ? languageMatch[1] : '';

      const poContent = generatePoContent(flattened, fileName, language);

      const outputPath = filePath.replace(/\.locales?\.json$/i, '.po');
      fs.writeFileSync(outputPath, poContent, 'utf-8');

      console.log(`✓ Converted: ${path.relative(ROOT_DIR, filePath)}`);
      console.log(`  → ${path.relative(ROOT_DIR, outputPath)}`);
      convertedCount++;
    } catch (error) {
      console.error(`✗ Error processing ${path.relative(ROOT_DIR, filePath)}:`);
      console.error(`  ${error.message}`);
    }
  }

  console.log(`\n✓ Successfully converted ${convertedCount} file(s).`);
}

main();
