#!/usr/bin/env node

/**
 * Usage:
 *   node generate-assets.js <folderPath>
 *
 * Requirements:
 * - If <folder>/index.d.ts exists and contains "declare module '*.xyz'",
 *   only those extensions will be considered.
 * - Generated file: <folder>/assets.ts
 */

const fs = require('fs');
const path = require('path');

const rootDir = process.argv[2];
if (!rootDir) {
  console.error('Usage: node generate-assets.js <folder>');
  process.exit(1);
}

if (!fs.existsSync(rootDir) || !fs.statSync(rootDir).isDirectory()) {
  console.error('[ERROR] Provided path is not a directory:', rootDir);
  process.exit(1);
}

/* ---------------------------------------------
 * 1. Parse index.d.ts for allowed extensions
 * --------------------------------------------- */
function extractExtensions(dtsPath) {
  if (!fs.existsSync(dtsPath)) return null;

  const content = fs.readFileSync(dtsPath, 'utf8');
  const regex = /declare module ['"]\*\.([a-zA-Z0-9]+)['"]/g;

  const extensions = [];
  let match;
  while ((match = regex.exec(content))) {
    extensions.push('.' + match[1].toLowerCase());
  }
  return extensions.length > 0 ? extensions : null;
}

const indexDtsPath = path.join(rootDir, 'index.d.ts');
const allowedExtensions = extractExtensions(indexDtsPath);

/* ---------------------------------------------
 * 2. Recursively collect asset files
 * --------------------------------------------- */
function isAllowedAsset(file) {
  if (!allowedExtensions) return true;
  return allowedExtensions.includes(path.extname(file).toLowerCase());
}

function walk(dir, base = dir) {
  const entries = fs.readdirSync(dir, { withFileTypes: true });
  let files = [];

  for (const entry of entries) {
    const fullPath = path.join(dir, entry.name);

    if (entry.isDirectory()) {
      files = files.concat(walk(fullPath, base));
    } else if (entry.isFile() && isAllowedAsset(entry.name)) {
      const relative = path.relative(base, fullPath).replace(/\\/g, '/');
      files.push(relative);
    }
  }

  return files;
}

const assetFiles = walk(rootDir);

/* ---------------------------------------------
 * 3. Create valid variable names from paths
 * --------------------------------------------- */
function toVarName(p) {
  return p
    .replace(/\.[^.]+$/, '') // remove extension
    .replace(/[^a-zA-Z0-9]+(.)?/g, (_, c) => (c ? c.toUpperCase() : ''))
    .replace(/^[^a-zA-Z]+/, ''); // must start with letter
}

/* ---------------------------------------------
 * 4. Build nested object structure from paths
 * --------------------------------------------- */
function buildNestedStructure(files) {
  const tree = {};

  for (const file of files) {
    const parts = file.split('/');
    const filename = parts.pop();
    const variableName = toVarName(file);

    let node = tree;

    // create nested folders
    for (const p of parts) {
      const key = toVarName(p);
      if (!node[key]) node[key] = {};
      node = node[key];
    }

    // final leaf entry
    node[toVarName(filename)] = variableName;
  }

  return tree;
}

const assetsTree = buildNestedStructure(assetFiles);

/* ---------------------------------------------
 * 5. Render object recursively
 * --------------------------------------------- */
function renderObject(obj, indent = 2) {
  const pad = ' '.repeat(indent);
  const entries = Object.entries(obj);

  return (
    '{\n' +
    entries
      .map(([key, value]) => {
        if (typeof value === 'string') {
          return `${pad}${key}: ${value} as string,`;
        }
        return `${pad}${key}: ${renderObject(value, indent + 2)}`;
      })
      .join('\n') +
    '\n' +
    ' '.repeat(indent - 2) +
    '}' +
    (indent > 2 ? ',' : '')
  );
}

/* ---------------------------------------------
 * 6. Generate import statements
 * --------------------------------------------- */
function generateImports(files) {
  return files
    .map((f) => {
      const varName = toVarName(f);
      const importPath = './' + f;
      return `import ${varName} from '${importPath}';`;
    })
    .join('\n');
}

/* ---------------------------------------------
 * 7. Write assets.ts
 * --------------------------------------------- */
const imports = generateImports(assetFiles);
const objectLiteral = renderObject(assetsTree, 2);

const output = `/* Auto-generated by generate-assets.js */

${imports}

export const assets = ${objectLiteral};
`;

const outFile = path.join(rootDir, 'assets.ts');
fs.writeFileSync(outFile, output, 'utf8');

console.log(`✔ assets.ts generated with ${assetFiles.length} assets`);
