name: clank8y

on:
  workflow_dispatch:
    inputs:
      prompt:
        type: string
        required: false

permissions:
  id-token: write

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Run clank8y
        uses: clank8y/clank8y@9c6ddcfcd4dddce84eea2f65b574017d5d4e8aa1
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_CLANK8Y_TOKEN }}
        with:
          prompt: ${{ inputs.prompt }}
          model: anthropic:claude-opus-4-7
